### ISSUE TITLE
You're running vue in dev mode in production

### ISSUE THREAD

**Issue by aDotInTheVoid** [DavidTParks/dev-portfolio-2.0#1]
From the console

```
You are running Vue in development mode.
Make sure to turn on production mode when deploying for production.
See more tips at https://vuejs.org/guide/deployment.html
```

This is on `davidparks.dev`, not a local build

**Comment by DavidTParks** [comment]
That's strange, I'm not seeing this when I inspect the console. Which browser are you on? Thank you for bringing it to my attention though!

**Comment by aDotInTheVoid** [comment]
Actualy it's fine. The message is coming from the codesandbox frame in https://davidparks.dev/blog/nuxt-table-of-contents-with-active-states/, not the main site itself. where it doesn't show. 

Sorry for the false alarm, and thanks for writing the article. I realy enjoyed it
